export * from './types.js';
export { ProjectBrainImpl } from './brain/brain.js';
export { BrainPersistence } from './brain/persistence.js';
export { LockManager } from './lock/manager.js';
export type { FileLock, LockGranularity, LockType, LockStatus, CodeRegion, LockState } from './types.js';
export type { LockRequest, LockResult } from './lock/types.js';
export { ConflictDetector } from './conflict/detector.js';
export { RegionConflictDetector } from './conflict/region-detector.js';
export { SemanticConflictDetector } from './conflict/semantic-detector.js';
export type { SemanticConflict, SemanticConflictReport } from './conflict/semantic-detector.js';
export { TaskStateMachine, canTransition } from './task/state-machine.js';
export type { TransitionRecord } from './task/state-machine.js';
export { createLogger, getGlobalLogs, clearGlobalLogs } from './logging/logger.js';
export type { LogEntry, LogFilter, Logger, LogLevel } from './logging/types.js';